ex1_e:
	../plug -f ex1.txt -d hw 'hello world' -g hw
	cat ex1.txt
ex1_c:
	../plug -f ex1.txt -u hw
	cat ex1.txt

ex2_e:
	../plug -f ex2.cpp -d code '	puts(hello world);' -g code
	cat ex2.cpp
ex2_c:
	../plug -f ex2.cpp -u code
	cat ex2.cpp
